version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/ingmarstein/tcp-multiplexer/cmd.version={{.Version}} -X github.com/ingmarstein/tcp-multiplexer/cmd.commit={{.Commit}} -X github.com/ingmarstein/tcp-multiplexer/cmd.date={{.Date}} -X github.com/ingmarstein/tcp-multiplexer/cmd.builtBy=goreleaser
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - image_templates:
      - "docker.io/ingmarstein/tcp-multiplexer:{{ .Version }}-amd64"
      - "docker.io/ingmarstein/tcp-multiplexer:latest-amd64"
      - "ghcr.io/ingmarstein/tcp-multiplexer:{{ .Version }}-amd64"
      - "ghcr.io/ingmarstein/tcp-multiplexer:latest-amd64"
    use: buildx
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "docker.io/ingmarstein/tcp-multiplexer:{{ .Version }}-arm64"
      - "docker.io/ingmarstein/tcp-multiplexer:latest-arm64"
      - "ghcr.io/ingmarstein/tcp-multiplexer:{{ .Version }}-arm64"
      - "ghcr.io/ingmarstein/tcp-multiplexer:latest-arm64"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
  - image_templates:
      - "docker.io/ingmarstein/tcp-multiplexer:{{ .Version }}-arm-v6"
      - "docker.io/ingmarstein/tcp-multiplexer:latest-arm-v6"
      - "ghcr.io/ingmarstein/tcp-multiplexer:{{ .Version }}-arm-v6"
      - "ghcr.io/ingmarstein/tcp-multiplexer:latest-arm-v6"
    use: buildx
    goarch: arm
    goarm: "6"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v6"
  - image_templates:
      - "docker.io/ingmarstein/tcp-multiplexer:{{ .Version }}-arm-v7"
      - "docker.io/ingmarstein/tcp-multiplexer:latest-arm-v7"
      - "ghcr.io/ingmarstein/tcp-multiplexer:{{ .Version }}-arm-v7"
      - "ghcr.io/ingmarstein/tcp-multiplexer:latest-arm-v7"
    use: buildx
    goarch: arm
    goarm: "7"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v7"
docker_manifests:
  - name_template: "ingmarstein/tcp-multiplexer:{{ .Version }}"
    image_templates:
      - "ingmarstein/tcp-multiplexer:{{ .Version }}-amd64"
      - "ingmarstein/tcp-multiplexer:{{ .Version }}-arm64"
      - "ingmarstein/tcp-multiplexer:{{ .Version }}-arm-v6"
      - "ingmarstein/tcp-multiplexer:{{ .Version }}-arm-v7"
  - name_template: "ingmarstein/tcp-multiplexer:latest"
    image_templates:
      - "ingmarstein/tcp-multiplexer:latest-amd64"
      - "ingmarstein/tcp-multiplexer:latest-arm64"
      - "ingmarstein/tcp-multiplexer:latest-arm-v6"
      - "ingmarstein/tcp-multiplexer:latest-arm-v7"
